def custom_song(greeting, location, adjective, action_verb, feeling, town, time, verb):
    print(f"{greeting}, it's {adjective}")
    print("I was wondering if after all these", time, "you'd like to", action_verb)
    print("To go over everything")
    print("They say that time's supposed to heal ya, but I ain't done much healing")
    print(f"{greeting}, can you hear me?")
    print(f"I'm in {location} dreaming about who we used to be")
    print("When we were younger and free")
    print("I've forgotten how it felt before", f"the {town} fell at our feet")
    print("There's such a difference between us")
    print("And a million", time)
    print("Hello from the", feeling)
    print("I must've called a thousand times")
    print("To tell you I'm sorry for everything that I've done")
    print("But when I call, you never seem to be home")
    print("Hello from the outside")
    print("At least I can say that I've tried")
    print("To tell you I'm sorry for breaking your heart")
    print("But it don't matter, it clearly doesn't", verb, "you apart anymore")
    print(f"{greeting}, how are you?")
    print("It's so typical of me to talk about myself, I'm sorry")
    print("I hope that you're well")
    print(f"Did you ever make it out of that {town} where nothing ever happened?")
    print("It's no secret that the both of us")
    print("Are running out of time")
    print("So hello from the", feeling)
    print("I must've called a thousand times")
    print("To tell you I'm sorry for everything that I've done")
    print("But when I call, you never seem to be home")
    print("Hello from the outside")
    print("At least I can say that I've tried")
    print("To tell you I'm sorry for breaking your heart")
    print("But it don't matter, it clearly doesn't", verb, "you apart anymore")

# Collect user input
greeting = input("Enter a greeting of your choice: ")
location = input("Enter a location or place of your choice: ")
adjective = input("Enter an adjective to describe yourself: ")
action_verb = input("Enter an action verb of your choice: ")
feeling = input("Enter a feeling or emotion of your choice: ")
town = input("Enter a town or city name: ")
time = input("Enter a word to describe a type of time. ex: day, period of days, year, : ")
verb = input("Enter a verb of your choice: ")

# Call the function
custom_song(greeting=greeting, location=location, adjective=adjective, action_verb=action_verb, feeling=feeling, town=town, time=time, verb=verb)
